### ISSUE TITLE
filter category group

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#1]
How can I get something like this?

example : 
![IMG_3386](https://user-images.githubusercontent.com/4959534/83957452-c85fad00-a868-11ea-859c-cfcb734229e8.GIF)

**Comment by joshbernfeld** [comment]
This could be implemented using a [PreviewController](https://www.pixelsdk.com/docs/latest/Classes/PreviewController.html) and a UICollectionView flow layout where cells are inserted when a top level group is clicked. For the time being, I'm going to mark this as a new feature request.

**Comment by janczakb** [comment]
@joshbernfeld I need this function because when there are many filters, the navigation is chaotic.

Is it now possible to easily modify UICollectionView?

**Comment by joshbernfeld** [comment]
Ah, I see.

One potential issue would be getting the same behavior for the UICollectionView that is also available on the CameraController.

Another potential option could be what Instagram does. A "Manage" button that allows users to enable/disable/reorder infrequently used filters:

![IMG_0073](https://user-images.githubusercontent.com/4284531/83992561-93556800-a905-11ea-9f62-b3e280f53b4f.PNG) ![IMG_0074](https://user-images.githubusercontent.com/4284531/83992454-348fee80-a905-11ea-954f-1f391db9072d.PNG)

**Comment by janczakb** [comment]
@joshbernfeld it's a weak solution for me. grouping is better because it is more readable. 

if we create photo editing applications and want to provide a lot of professional filters (100-200 filters) it must be easy and legible.

I think that many people would be happy with the function that could be used to divide the filters into categories. 

I would like to create categories myself, e.g. black and white, vibrant, Portrait, Urban, etc., and I would not like to search for filters scrolling forever to find what I am looking for.

I would like to be able to create categories, e.g. black and white, vivid, portrait, urban etc. and I would not like to look for filters that scroll forever to find the one that I want to use. 

additionally, one could add in the first position the "all filters" tile, which would open a filter gallery in a pop-up window on the screen. (fullscreen)



![0F82015A-815D-4557-9114-EC1076C6FD1E](https://user-images.githubusercontent.com/4959534/84024888-f4734f00-a98a-11ea-8388-4dee08d1266e.gif)

**Comment by janczakb** [comment]
@joshbernfeld This solution is even better.
I would like to be able to use such functionality because it is a great convenience in searching for filters.


![prezentacja](https://user-images.githubusercontent.com/4959534/84155890-2a870080-aa69-11ea-8014-0c6957c518f9.gif)

**Comment by joshbernfeld** [comment]
We should be able to provide a simple category example once support is added for custom view controllers in the EditController

**Comment by joshbernfeld** [comment]
Custom view controllers in the EditController are now available in the latest version of Pixel SDK (7.0.0). I have attached an example project which demonstrates implementing categories in the EditController. You will need to run `pod install` on this example.

[Categories Example](https://github.com/GottaYotta/PixelSDK/files/4817961/Categories.Example.zip)

A custom controller can be specified by setting the modes (tabs) of your EditController in the EditController delegate call:
```swift
extension ViewController: EditControllerDelegate {
    // Called after the EditController's view did load.
    func editController(_ editController: EditController, didLoadEditing session: Session) {
        // Initialize our custom controller
        let controller = UIViewController()
        // Set the tabs of the EditController
        editController.modes = [.custom(title: "Custom", controller: controller), .trim, .adjust]
    }
}
```
or if you are simply initializing the EditController on your own:
```swift
let session = Session(image: UIImage(named: "test_image")!)
let editController = EditController(session: session)
editController.delegate = self

// Initialize our custom controller
let controller = UIViewController()
// Set the tabs of the EditController
editController.modes = [.custom(title: "Custom", controller: controller), .trim, .adjust]
```
Note that although the `.trim` tab is included, it will only be shown if you are editing a video session.

**Comment by janczakb** [comment]
@joshbernfeld I have only one problem in compactControls mode : 

without compactControls mode: 
<img width="407" alt="Zrzut ekranu 2020-06-23 o 14 02 00" src="https://user-images.githubusercontent.com/4959534/85401498-64243500-b55a-11ea-8ac1-5eb39d1a213a.png">
with compactControls mode: 
<img width="387" alt="Zrzut ekranu 2020-06-23 o 14 02 28" src="https://user-images.githubusercontent.com/4959534/85401523-71d9ba80-b55a-11ea-9254-f23af9b8235e.png">

Clips filter names

**Comment by joshbernfeld** [comment]
You will want to play around with the collection view height constraints, collection view contentInsets, and cell sizes depending on your layout. The example sets the gallery cell size with `galleryFlowLayout.itemSize = CGSize(width: 87, height: 108)`.

I have made the needed changes for compact mode in a [new example project](https://github.com/GottaYotta/PixelSDK/files/4822444/Categories.Example.zip).

**Comment by janczakb** [comment]
@joshbernfeld thanks. 

I have a question for you. I installed macOS in the Big Sur version and there was a problem with one library (I know there is still a lot of time until the official release).

But maybe it can be solved quickly (Otherwise I will have to restore the older version of the system).

I get this message at the last stage of project complication:

Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: /Users/.../Desktop/.../Pods/PixelSDK/PixelSDK.framework/Modules/PixelSDK.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by joshbernfeld** [comment]
That is something we should be able to fix on our end. I will comment here when a new release is available that attempts to resolve the issue.

**Comment by joshbernfeld** [comment]
A new release is now available (7.0.2) and should resolve your issue. Please run `pod update` and clean your build folder. Let me know if this fixes your issue.

**Comment by joshbernfeld** [comment]
@janczakb This problem appears to be related to Xcode 12 Beta and Swift 5.3 Beta. If you are able to run Xcode 11.5 it should resolve your issue until we officially add support for Xcode 12.

**Comment by joshbernfeld** [comment]
@janczakb We should have a release ready for Xcode 12 in a matter of hours. I am moving discussion of this topic to #20

**Comment by joshbernfeld** [comment]
Attached is a new [sample project](https://github.com/GottaYotta/PixelSDK/files/4829329/Categories.Example.zip) which has been updated for PixelSDK 8.0.0 and supports Xcode 12/Swift 5.3.
