### ISSUE TITLE
Possibility to block individual filters

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#10]
Possibility to block individual filters (available for a fee) + option to add actions after clicking on a blocked filter (displaying the option to buy a subscription - to your own settings).

**Comment by joshbernfeld** [comment]
You can now add your custom functionality to the [categories example](https://github.com/GottaYotta/PixelSDK/issues/1#issuecomment-647983468) by overlaying a lock UIImageView on the gallery cells + adding any additional subscription functionality in the custom controller.
