### ISSUE TITLE
Is it possible to add support for applying a filter on uiimage thumbnail?

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#11]
Is it possible to add support for applying a given filter on uiimage?
I made a preliminary gallery of filters and after selecting a category a preview is shown (attachment).
I would like to display a list of filters that are included in the category (preview).
At the moment, each thumbnail is the same. I would have to create a separate graphic file for each.

Can it be simplified somehow to generate a thumbnail of the selected filter?

![EXAMPLE](https://user-images.githubusercontent.com/4959534/84606966-73e0b100-aeaa-11ea-9525-3c12e5ebd705.jpg)

**Comment by joshbernfeld** [comment]
Great question. We were in the process of exposing this functionality for feature request #1 custom controllers in the EditController.

We can move thumbnail filters into the next release which will be available in ~5 hours. I will comment here when the release is available with instructions.

**Comment by joshbernfeld** [comment]
This now available in the latest release (6.1.0). Please run `pod update`.

To generate multiple thumbnails each with a different filter you can do the following:
```swift
let session = Session(image: UIImage(named: "test_image")!)

// Mark the session as transient so it does not appear in the users drafts and persist on disk
session.isTransient = true

// Choose Filters
let filters = [
    SessionFilterMontana(),
    SessionFilterMelrose(),
    SessionFilterWilshire(),
    SessionFilterAbbotKinney()
]

// Generate thumbnails
for filter in filters {
    session.image!.requestThumbnail(boundingSize: CGSize(width: 200, height: 200), contentMode: .contentAspectFill, filter: filter) { (image) in
        if let image = image {
            print("Generated Thumbnail: \(image)")
        }
        else {
            print("Failed to generate thumbnail")
        }
    }
}
```

And if you have a video session, simply select which segment:
```swift
session.video!.videoSegments.first!.requestThumbnail(boundingSize: CGSize(width: 200, height: 200), contentMode: .contentAspectFill, filter: filter) { (image) in
    if let image = image {
        print("Generated Thumbnail: \(image)")
    }
    else {
        print("Failed to generate thumbnail")
    }
}
```

**Comment by janczakb** [comment]
@joshbernfeld great! 
Do you know when support for custom view controllers in the EditController will be added?

**Comment by joshbernfeld** [comment]
It is currently being added and should be completed in 10-15 days. Hopefully sooner.
