### ISSUE TITLE
Is it possible to create new filters dynamically?

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#12]
I would like to offer a very large range of filter galleries, which is why I started thinking about creating an online gallery from which it would be possible to download selected packages to the phone. (The ios application must have a limited file size according to Apple guidelines)

At the moment, to create a filter, I have to create a separate file for each. 

I may be wrong and maybe it is already possible.

**Comment by joshbernfeld** [comment]
If your main concern is application file size, the simplest option would be to create the `SessionFilter` classes normally and have them added at compile time. The classes themselves once compiled are pretty much negligible.

The main concern would be any supporting images for each filter (lookup.png files). You can store the lookup images on a server, and when the user subscribes to a certain set of filters, download that set of lookup images from the server.
