### ISSUE TITLE
Impossible export in production with free version

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#13]
I am currently using the free version with watermark, I added the first version of the application to the app store and export does not work in it (Should it be that way?)

**Comment by joshbernfeld** [comment]
The free version was really intended for demonstration/development purposes. The export was intentionally disabled in production to prevent confusion. Now we see that this can be confusing.

Would you like to be able to export images with the watermark when on the app store?

**Comment by janczakb** [comment]
@joshbernfeld Currently, this is my first application, at the moment I didn't mind the watermark

**Comment by joshbernfeld** [comment]
@janczakb That is very exciting!

If you want to be able to export with the watermark when in production, you can replace the following in your export function:
```swift
if let error = error {
    print("Unable to export image: \(error)")
    return
}
```
with:
```swift
if let error = error {
    if case .watermarked = error {
        
    }
    else {
        print("Unable to export: \(error)")
        return
    }
}
```

We sincerely apologize for the inconvenience.
