### ISSUE TITLE
Add Xcode 12 Support

### ISSUE THREAD

**Issue by joshbernfeld** [GottaYotta/PixelSDK#20]
#### What are the steps to reproduce?
Run on Xcode 12

#### What did you expect to happen?
Build succeeds

#### What happened instead?
Build fails with errors inside .swiftinterface file

**Comment by joshbernfeld** [comment]
Support has been added for Xcode 12 and Swift 5.3 in the latest release. @janczakb

**Comment by janczakb** [comment]
@joshbernfeld now he returns me such messages:

Failed to build module 'PixelSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.16.9 clang-1200.0.22.5)'

Compiling for iOS 11.0, but module 'GPUImage' has a minimum deployment target of iOS 12.0:

**Comment by joshbernfeld** [comment]
Can you please post the contents of your `Podfile.lock` so we can verify you are on the latest version of Pixel SDK

**Comment by janczakb** [comment]
@joshbernfeld 


PODS:
  - PixelSDK (8.0.0):
    - PixelSDK-GPUImage2 (~> 5.0.0)
  - PixelSDK-GPUImage2 (5.0.0)

DEPENDENCIES:
  - PixelSDK

SPEC REPOS:
  trunk:
    - PixelSDK
    - PixelSDK-GPUImage2

SPEC CHECKSUMS:
  PixelSDK: 9de7082f40467fe22a3424ae2595896bc42a2a90
  PixelSDK-GPUImage2: 264f0dae8f5e3b1b7713235c35923be87043f708

PODFILE CHECKSUM: 878131697e584e2f0afbe7b9abb3b03ff355c721

COCOAPODS: 1.9.3

**Comment by joshbernfeld** [comment]
Please also verify the following build setting for target `PixelSDK-GPUImage2`
<img width="1649" alt="Screen Shot 2020-06-25 at 4 11 55 PM" src="https://user-images.githubusercontent.com/4284531/85804546-cae25380-b6fe-11ea-87b8-9234f86b887c.png">

**Comment by janczakb** [comment]
@joshbernfeld ok, now works
