### ISSUE TITLE
Hey guys we need this sdk in react-native

### ISSUE THREAD

**Issue by codal-mpawar** [GottaYotta/PixelSDK#24]
If any one have an idea please let's know any library or something.

**Comment by joshbernfeld** [comment]
Dear codal-mpawar,

Thank you for reaching out. We do hope to offer React Native support in the future.

For the time being, you could attempt to [create your own iOS Native module](https://reactnative.dev/docs/native-modules-ios) for just the Pixel SDK methods you need. 

All the best,

Josh

Pixel SDK Support
