### ISSUE TITLE
[question] - Remove Audio on video export

### ISSUE THREAD

**Issue by umwelt** [GottaYotta/PixelSDK#26]
Hi, any suggestion to remove audio from a video while exporting the video?

Thanks

**Comment by joshbernfeld** [comment]
We are working on a solution and will get back to you shortly.

If you have any additional questions, please let us know.

**Comment by joshbernfeld** [comment]
This feature has been added to the latest version of Pixel SDK `11.0.3`

Please update your installation first by running the following command:

`pod update PixelSDK`

After updating, be sure to clean your project before building.

To export without audio, provide an empty dictionary for the `audioEncodingSettings`. For example:

```swift
if let video = session.video {
    VideoExporter.shared.export(video: video, audioEncodingSettings: [:], completion: { error in
        if let error = error {
            print("Unable to export video: \(error)")
            return
        }

        print("Finished video export at URL: \(video.exportedVideoURL)")
    })
}
```

If you have any additional questions, please let us know.

**Comment by umwelt** [comment]
@joshbernfeld  
Thanks for the quick response - works as expected 

We are about to go live with Pixel SDK integrated in our app - WodPod - The SDK works just perfect.

**Comment by joshbernfeld** [comment]
Glad to hear it. Good luck!
