### ISSUE TITLE
Not Running On M1 Chip

### ISSUE THREAD

**Issue by arjunshukla22** [GottaYotta/PixelSDK#28]
its Not working on M! Chip 

Screen Shot attached for Reference.

<img width="1552" alt="Screenshot 2021-12-15 at 10 37 35 AM" src="https://user-images.githubusercontent.com/40709718/146129483-952ca703-5d0a-4ef2-b1bd-10d38bf05770.png">

**Comment by joshbernfeld** [comment]
Hi Arjun,

Thank you for reaching out.

In order for us to properly diagnose the issue, could you please attach your `Podfile.lock` file located in the root of your project folder. Additionally, please let us know what version of Xcode is installed on your machine. 

Are you able to successfully build on a physical device?

All the best,

Josh

**Comment by arjunshukla22** [comment]
Sure joshberned, 

I'm. using Xcode 12.5.1

Please find files
[Podfile.lock.zip](https://github.com/GottaYotta/PixelSDK/files/7737337/Podfile.lock.zip)

**Comment by joshbernfeld** [comment]
Hi Arjun,

Please update to the latest version of Xcode, clean your project, and then rebuild.

All the best,

Josh

**Comment by arjunshukla22** [comment]
Thanx Bro , 
Its working fine on 13.1. 

How can we remove Watermark From Image & video ?

**Comment by joshbernfeld** [comment]
The watermark can be removed by [generating an API key](https://www.pixelsdk.com/dashboard/api-keys/) and specifying it in your `application(_, didFinishLaunchingWithOptions:)` of your App Delegate:

```swift
import PixelSDK

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

    PixelSDK.setup("YOUR API KEY")

    return true
}
```
