### ISSUE TITLE
on iPhone X, XS, 11 should be added space below

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#3]
the content overlaps the ios interface. a space should be added

Example : 

![1DDC05EE-51ED-4538-A635-F6DEDC8D2985](https://user-images.githubusercontent.com/4959534/83973035-0352f680-a8e4-11ea-8474-92920dd65e3d.jpeg)

**Comment by joshbernfeld** [comment]
@janczakb If you download the [sample project](https://github.com/GottaYotta/PixelSDK/archive/master.zip) and run it on an iPhone X, XS, 11 the content insets at the top and bottom should appear like so: 

<img width="295" alt="Screen Shot 2020-06-07 at 8 10 46 PM" src="https://user-images.githubusercontent.com/4284531/83989358-03122580-a8fb-11ea-844a-04bce8a750be.png">

Can you please verify that you have a `LaunchScreen.storyboard` file located in your Xcode project and that your `Info.plist` has the following line: 
```xml
<key>UILaunchStoryboardName</key>
<string>LaunchScreen</string>
```
Or that you have manually include a launch image for the iPhone X:

<img width="766" alt="Screen Shot 2020-06-07 at 8 08 29 PM" src="https://user-images.githubusercontent.com/4284531/83989434-3e145900-a8fb-11ea-8ede-f063b5d3ae70.png">

If you do not have this, your application will default over to iPhone 6, 7, 8 behavior.

**Comment by janczakb** [comment]
@joshbernfeld My project has the "LaunchScreen.storyboard" file and the corresponding entry in the "Info.plist" file

**Comment by joshbernfeld** [comment]
Could you attach a simple project that reproduces the bug? We are having difficulty reproducing the issue.

-Josh

**Comment by joshbernfeld** [comment]
Your sample project [here](https://github.com/GottaYotta/PixelSDK/issues/6#issuecomment-640907745) replicates the issue. We are working on a solution and will get back to you shortly.

**Comment by joshbernfeld** [comment]
This has been fixed in the latest release available now.
