### ISSUE TITLE
Sudden Crash: PixelSDK.PreviewCropController: 0x11402d800> should have parent view controller:(null) 

### ISSUE THREAD

**Issue by umwelt** [GottaYotta/PixelSDK#31]
### What are the steps to reproduce?
Select video and try to move to edition

Im having this crash 
:<PixelSDK.PreviewCropController: 0x11402d800> should have parent view controller:(null) but actual parent is:<PixelSDK.EditController: 0x11402d200>

Any Idea?

**Comment by joshbernfeld** [comment]
Dear umwelt,

Thank you for reaching out to Pixel SDK support.

For me to better assist you I will need some additional information.

Could you please attach a copy of your `Podfile.lock` file located at the root of your project?

Additionally, please let me know what version of Xcode you have installed.

All the best,

Josh

Pixel SDK Support
