### ISSUE TITLE
Audio overlay

### ISSUE THREAD

**Issue by nickhward** [GottaYotta/PixelSDK#32]
How could I go about adding a section to allow for recording of audio from the user to overlay onto a video using this sdk?

**Comment by joshbernfeld** [comment]
The SDK does not currently support audio manipulation. If you wish to overlay custom audio onto a video, you would need to use [AVMutableComposition](https://developer.apple.com/documentation/avfoundation/avmutablecomposition) and [AVMutableVideoComposition](https://developer.apple.com/documentation/avfoundation/avmutablevideocomposition).
