### ISSUE TITLE
zoom support

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#4]
Example 
![6EB2ED87-AAE9-4BCD-956C-AD2E478372A8](https://user-images.githubusercontent.com/4959534/83973124-8d9b5a80-a8e4-11ea-8e3d-ba215d911af6.gif)

**Comment by joshbernfeld** [comment]
Unfortunately zooming would conflict with text and stickers (coming in the near future). The pinch and pan gesture recognizers will be needed for that instead.

Thank you for your great suggestion!

**Comment by joshbernfeld** [comment]
I should also note that you could display your own preview using a [PreviewController](https://www.pixelsdk.com/docs/latest/Classes/PreviewController.html) and place that into a UIScrollView.

**Comment by leojkwan** [comment]
hey @joshbernfeld your tool is great, wondering whether your mention of stickers is in the near future? I'm guessing it'd be similar to a basic canva like tool? That would be so awesome.

**Comment by joshbernfeld** [comment]
@leojkwan thank you! Yes we do plan to add stickers in the near future.
